name: ${project.name}
main: me.ryanhamshire.GraviTree.GraviTree
authors: ['Big_Scary', 'RoboMWM', 'DmitryRendov']
version: ${project.version}
api-version: 1.14
commands:
   treesfall:
      description: Toggles tree blocks falling when a tree is chopped.
      usage: /TreesFall
permissions:
    gravitree.chop:
        description: Grants permission to apply gravity to chopped trees.
        default: op